name: ci-cd/develop

on:
  push:
    branches: ["develop"]

env:
  DOCKER_HUB_USERNAME: 242912
  DOCKER_HUB_REPOSITORY: 242912/sunset-house
  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  SSH_HOST: 54.37.233.59
  SSH_PORT: 22
  SSH_USER: ubuntu
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        env:
          CONTENTFUL_GRAPHQL_ENDPOINT: ${{ secrets.CONTENTFUL_GRAPHQL_ENDPOINT }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_REVALIDATE_SECRET: ${{ secrets.CONTENTFUL_REVALIDATE_SECRET }}
          PORT: 5000
        with:
          context: .
          build-args: |
            "CONTENTFUL_GRAPHQL_ENDPOINT=${{ secrets.CONTENTFUL_GRAPHQL_ENDPOINT }}"
            "CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }}"
            "CONTENTFUL_SPACE_ID=${{ secrets.CONTENTFUL_SPACE_ID }}"
            "CONTENTFUL_REVALIDATE_SECRET=${{ secrets.CONTENTFUL_REVALIDATE_SECRET }}"
            "PORT=5000"
          file: ./prod.Dockerfile
          push: true
          tags: ${{ env.DOCKER_HUB_REPOSITORY }}:latest
      - name: Upload deployment configuration
        uses: actions/upload-artifact@v4
        with:
          name: deployment-configuration
          path: deployment/dev/docker-compose-sh-dev-web.yaml
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download deployment configuration
        uses: actions/download-artifact@v4
        with:
          name: deployment-configuration
      - name: Deploy to VPS
        shell: bash
        env:
          CONTENTFUL_GRAPHQL_ENDPOINT: ${{ secrets.CONTENTFUL_GRAPHQL_ENDPOINT }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_SPACE_ID: ${{ secrets.CONTENTFUL_SPACE_ID }}
          CONTENTFUL_REVALIDATE_SECRET: ${{ secrets.CONTENTFUL_REVALIDATE_SECRET }}
          PORT: 5000
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa


          # Create an environment file
          echo "CONTENTFUL_GRAPHQL_ENDPOINT=$CONTENTFUL_GRAPHQL_ENDPOINT" > .env
          echo "CONTENTFUL_ACCESS_TOKEN=$CONTENTFUL_ACCESS_TOKEN" >> .env
          echo "CONTENTFUL_SPACE_ID=$CONTENTFUL_SPACE_ID" >> .env
          echo "CONTENTFUL_REVALIDATE_SECRET=$CONTENTFUL_REVALIDATE_SECRET" >> .env
          echo "PORT=$PORT" >> .env
          # ... append other environment variables ...

          # Transfer the environment file and Docker Compose file to VPS
          scp -o StrictHostKeyChecking=no -P $SSH_PORT sunset-house/.env $SSH_USER@$SSH_HOST:~

          scp -o StrictHostKeyChecking=no -P $SSH_PORT docker-compose-sh-dev-web.yaml $SSH_USER@$SSH_HOST:docker-compose-sh-dev-web.yaml
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST docker compose -f docker-compose-sh-dev-web.yaml pull
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST docker compose -f docker-compose-sh-dev-web.yaml up -d
          ssh -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST docker image prune --all --force
